### ISSUE TITLE
Execute permissions are not set on downloaded ipfs daemon causing unexecutable error.

### ISSUE THREAD

**Issue by muksihs** [RHazDev/IPFS-Daemon#5]
```Java
java.io.IOException: Cannot run program "./ipfs": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:528)
	at fr.rhaz.ipfs.IPFSDaemonKt.process(IPFSDaemon.kt:130)
	at fr.rhaz.ipfs.IPFSDaemon.process(IPFSDaemon.kt:74)
	at tests.Ipfs.setup(Ipfs.java:17)
```

```Java
private IPFSDaemon ipfsd;
	@BeforeTest
	public void setup() throws InterruptedException{
		ipfsd = new IPFSDaemon();
		ipfsd.download();
		ipfsd.process(new String[0]);
	}
```

**Comment by muksihs** [comment]
Workaround:

```Java
		ipfsd = new IPFSDaemon();
		ipfsd.download();
		ipfsd.getBin().setExecutable(true);
```

**Comment by Hazae41** [comment]
Fixed in https://github.com/RHazDev/IPFS-Daemon/commit/a8d16bbff2befa109d0a820dbca02947b8dc05ef
